# --- !Ups

CREATE TABLE PRIORITIES(ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255) NOT NULL UNIQUE);

INSERT INTO PRIORITIES(NAME) VALUES('LOW');
INSERT INTO PRIORITIES(NAME) VALUES('MEDIUM');
INSERT INTO PRIORITIES(NAME) VALUES('HIGH');

ALTER TABLE TICKETS ADD COLUMN PRIORITY INT;
UPDATE TICKETS SET PRIORITY = 1;
ALTER TABLE TICKETS MODIFY COLUMN PRIORITY INT NOT NULL;
ALTER TABLE TICKETS ADD CONSTRAINT FK_PRIORITY_ID FOREIGN KEY (PRIORITY) REFERENCES PRIORITIES(ID);

INSERT INTO PROJECTS("NAME", "DESCRIPTION") VALUES('DEFAULT_PROJECT', 'DEFAULT_PROJECT');
ALTER TABLE TICKETS ADD COLUMN PROJECT INT;
UPDATE TICKETS SET PROJECT = SELECT LAST_INSERT_ID();
ALTER TABLE TICKETS MODIFY COLUMN PROJECT INT NOT NULL;
ALTER TABLE TICKETS ADD CONSTRAINT FK_PROJECT_ID FOREIGN KEY (PROJECT) REFERENCES "PROJECTS"("ID");


CREATE TABLE TICKET_STATES(ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255) NOT NULL UNIQUE);

INSERT INTO TICKET_STATES(NAME) VALUES('OPENED');
INSERT INTO TICKET_STATES(NAME) VALUES('IN_WORK');
INSERT INTO TICKET_STATES(NAME) VALUES('IN_REVIEW');
INSERT INTO TICKET_STATES(NAME) VALUES('DONE');
INSERT INTO TICKET_STATES(NAME) VALUES('WILL_NOT_DO');

ALTER TABLE TICKETS ADD COLUMN STATE INT;
UPDATE TICKETS SET STATE = 1;
ALTER TABLE TICKETS MODIFY COLUMN STATE INT NOT NULL;
ALTER TABLE TICKETS ADD CONSTRAINT FK_STATE_ID FOREIGN KEY (STATE) REFERENCES TICKET_STATES(ID);

# --- !Downs

ALTER TABLE TICKETS DROP CONSTRAINT FK_PRIORITY_ID;
ALTER TABLE TICKETS DROP COLUMN PRIORITY;
DROP TABLE PRIORITIES;